---
server:
  port: 8080
  contextPath: /SpringBootCRUDApp
---
spring:
   profiles: local, default
datasource:
  sampleapp:
    url: jdbc:h2:~/test
    username: SA
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
---
spring:
  profiles: prod
datasource:
  sampleapp:
    url: jdbc:mysql://localhost:3306/webapp
    username: amercado
    password: BJzVyeGPHyh3z7CF68jkhe3X+BJzVyeGPHyh3z7CF68jkhe3X#34
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
http:
  multipart:
    max-file-size: 500KB
    max-request-size: 500KB
    
